CREATE SCHEMA サンプル;

CREATE TABLE サンプル.アクション
(
    管理番号 CHARACTER(6) PRIMARY KEY,
    名称 VARCHAR(20) NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE SCHEMA 商品;

CREATE TABLE 商品.商品
(
    商品番号 CHARACTER (10) PRIMARY KEY,
    名称 VARCHAR (20) NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)